import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import {
  Combine,
  Search,
  Bell,
  Upload,
} from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};
const headerContent = (
  <>
    <div className="text-xl font-bold text-blue-600 flex items-center gap-2">
      <Combine className="lucide lucide-combine" width={24} height={24} />
    </div>

    <div className="w-1/2 max-w-xl relative">
      <Search
        className="lucide lucide-search absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400"
        width={20}
        height={20}
      />
      <input
        type="search"
        placeholder="ค้นหาเอกสารด้วยคำสำคัญ"
        className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
      />
    </div>

    <div className="flex items-items-center">
      <button
        className="p-2 rounded-full hover:bg-gray-100 text-gray-500 mr-2"
        title="การแจ้งเตือน"
      >
        <Bell className="lucide lucide-bell" width={24} height={24} />
      </button>
      <div
        className="w-9 h-9 rounded-full bg-blue-500 text-white flex items-center justify-center font-semibold cursor-pointer"
        title="สมชาย ทดสอบ"
      >
        สท
      </div>
    </div>
  </>
);

// import { usePathname } from "next/navigation";

// const navigationItems = () => {
//   const pathname = usePathname();

//   return (
//     <>
//       <a
//         href="/dashboard"
//         className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium ${
//           pathname === "/dashboard"
//             ? "text-blue-700 bg-blue-100"
//             : "text-gray-700 hover:bg-gray-100"
//         }`}
//       >
//         <Files className="lucide lucide-files" width={18} height={18} />
//         เอกสารทั้งหมด
//       </a>
//       <a
//         href="#"
//         className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium ${
//           pathname === "#"
//             ? "text-blue-700 bg-blue-100"
//             : "text-gray-700 hover:bg-gray-100"
//         }`}
//       >
//         <Clock className="lucide lucide-clock" width={18} height={18} />
//         เพิ่มล่าสุด
//       </a>

//       <a
//         href="/dashboard/share"
//         className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium ${
//           pathname === "/dashboard/share"
//             ? "text-blue-700 bg-blue-100"
//             : "text-gray-700 hover:bg-gray-100"
//         }`}
//       >
//         <Share2 className="lucide lucide-share-2" width={18} height={18} />
//         แชร์ให้ฉัน
//       </a>
//       <a
//         href="#"
//         className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium ${
//           pathname === "#"
//             ? "text-blue-700 bg-blue-100"
//             : "text-gray-700 hover:bg-gray-100"
//         }`}
//       >
//         <Folder className="lucide lucide-folder" width={18} height={18} />
//         เอกสารของฉัน
//       </a>
//       <a
//         href="#"
//         className={`flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium ${
//           pathname === "#"
//             ? "text-blue-700 bg-blue-100"
//             : "text-gray-700 hover:bg-gray-100"
//         }`}
//       >
//         <Trash2 className="lucide lucide-trash-2" width={18} height={18} />
//         ถังขยะ
//       </a>
//     </>
//   );
// };


const uploadButton = (
  <button className="w-full bg-blue-600 text-white rounded-lg px-4 py-2 flex items-center justify-center gap-2 hover:bg-blue-700 mb-6">
    <Upload className="lucide lucide-upload" width={20} height={20} />
    อัปโหลดเอกสาร
  </button>
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>

              {children}

          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
